/**
 * PDF Pagination Constants - matches CRM
 * Page: A4 297mm = 1123px, 60px top + 60px bottom padding = 1003px content area
 */

export const PDF_PAGINATION = {
  PAGE_PADDING: 60,
  A4_HEIGHT_PX: 1123,
  HEIGHT_BUFFER: 16,

  AIRPORT_PICKUP_HEIGHT: 44 + 170,
  AIRPORT_DROPOFF_HEIGHT: 44 + 170,

  ACCOMMODATION_HEADER_HEIGHT: 44,
  HOTEL_ITEM_HEIGHT: 200,

  VISA_HEADER_HEIGHT: 44,
  VISA_ITEM_HEIGHT: 102,

  ITINERARY_DAY_HEADER_HEIGHT: 48,
  ITINERARY_DAY_CONTINUATION_HEIGHT: 48,
  ITINERARY_ACTIVITY_HEIGHT: 155,

  TOTAL_ROW_HEIGHT: 110,

  ADDON_DEAL_HEADER_HEIGHT: 44,
  ADDON_DEAL_CARD_HEIGHT: 90,

  ADDON_TRANSFER_HEADER_HEIGHT: 44,
  ADDON_TRANSFER_CARD_HEIGHT: 75,

  ADDON_HOTEL_SERVICE_HEADER_HEIGHT: 44,
  ADDON_HOTEL_SERVICE_CARD_HEIGHT: 75,
} as const;

export const AVAILABLE_PAGE_HEIGHT =
  PDF_PAGINATION.A4_HEIGHT_PX - PDF_PAGINATION.PAGE_PADDING * 2;
